
#install
- name: Install InfluxDB data container
  docker_volume:
    name: influxdb_data

- name: Set influx tmp config directory
  file:
    path: /tmp/influxdb/scripts
    state: directory
    recurse: true
  become: true

- name: Copy SQL init script
  template:
    src: influxdb/influxdb-init.iql.j2
    dest: /tmp/influxdb/scripts/influxdb-init.iql
    mode: 'u=rwX,g=rX,o=rX'
    owner: influxdb
    group: influxdb
  register: influxdb_init_script

- name: Set database retention
  shell: 'docker run --rm -e INFLUXDB_HTTP_AUTH_ENABLED=true \
         -e INFLUXDB_ADMIN_USER={{ influx_admin_user }} \
         -e INFLUXDB_ADMIN_PASSWORD={{ influx_admin_password }} \
         -v /var/lib/influxdb:/var/lib/influxdb \
         -v /etc/influxdb/scripts:/docker-entrypoint-initdb.d \
         influxdb /init-influxdb.sh > /dev/null'
  when: influxdb_init_script is defined and influxdb_init_script.changed

- name: Install InfluxDB
  docker_container:
    name: influxdb
    image: "{{ docker_containers.influxdb.image }}"
    state: started
    restart: yes
    restart_policy: on-failure
    restart_retries: 4
    privileged: false
    purge_networks: no
    ports:
        - 8083:8083
        - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
    env:
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
      INFLUXDB_DB: "{{ influx_database_name }}"
      INFLUXDB_ADMIN_USER: "{{ influx_admin_user }}"
      INFLUXDB_ADMIN_PASSWORD: "{{ influx_admin_password }}"
